version: "3"

services:
  metabase-db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    environment:
        POSTGRES_USER: adminUser
        POSTGRES_PASSWORD: 11235813
        PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
        - /Users/plume/Workspace/metabase/db:/var/lib/postgresql/data
        - ./docker/services/postgres/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminUser"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: postgres
        MB_DB_PORT: 5432
        MB_DB_USER: adminUser
        MB_DB_PASS: 11235813
        MB_DB_HOST: metabase-db
    ports:
      - "3030:3000"
    volumes:
      - /Users/plume/Workspace/metabase/data:/metabase-data
    ulimits:
      nofile: 51200
    depends_on:
      - metabase-db
    links:
      - metabase-db
  mageai:
    image: mageai/mageai
    container_name: mageai
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    command: /app/run_app.sh mage start mainProj
    ports:
      - "6789:6789"
